version: "3.3"

services:
  scrapmon-ci:
    image: scrapmon-ci
    build:
      context: ./
      dockerfile: ./scripts/Dockerfile
    container_name: scrapmon-ci
    
    environment:
      PRINT_SCRAPE_HTTP_ADDR: ":8080"
      PRINT_SCRAPE_ENV: "prod"
      PRINT_SCRAPE_DB_HOST: "scrapmon-db"
      PRINT_SCRAPE_DB_PORT: "5432"
      PRINT_SCRAPE_DB_USER: "postgres"
      PRINT_SCRAPE_DB_PASSWORD: "password"
      PRINT_SCRAPE_DB_NAME: "scrapmon"
    depends_on:
      - scrapmon-db
  scrapmon-db:
    ports:
      - "5432:5432"