version: "3.3"

services:
  print-scrape-ci:
    image: print-scrape-ci
    build:
      context: ./
      dockerfile: ./scripts/Dockerfile
    container_name: print-scrape-ci
    environment:
      PRINT_SCRAPE_HTTP_ADDR: ":8080"
      PRINT_SCRAPE_ENV: "prod"
      PRINT_SCRAPE_DB_HOST: "print-scrape-db"
      PRINT_SCRAPE_DB_PORT: "5432"
      PRINT_SCRAPE_DB_USER: "postgres"
      PRINT_SCRAPE_DB_PASSWORD: "password"
      PRINT_SCRAPE_DB_NAME: "print-scrape"
    depends_on:
      - print-scrape-db
  # squid:
  #   container_name: squid
  #   hostname: squid
  #   image: squid:latest
  #   # env_file: 
  #   #   - ./squid-proxy-list.env
  #   environment: 
  #     VISIBLE_HOSTNAME: docker-squid4-print-scrape
  #     PROXYCHAIN: "yes"
  #     PROXYCHAIN_TYPE: dynamic_chain
  #     USER: root
  #   volumes:
  #     - ./proxychains.conf:/etc/extrachains.conf
  #     - ./squid.conf:/etc/squid4/squid.conf
  #   ports:
  #     - "3128:3128"
  print-scrape-db:
    image: postgres:12.0
    container_name: print-scrape-db
    hostname: print-scrape-db
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "print-scrape"
      POSTGRES_PORT: "5432"
    ports:
      - "5432:5432"